interface IProductCards {
    specie: string,
    title: string,
    price?: number,
    newPrice?: number,
    oldPrice?: number,
    unit: number,
    src: string,
    freshness: boolean,
    discount: boolean,
    measurement: string
}

export const products: IProductCards[] = [
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack",
        newPrice: 30,
        oldPrice: 47,
        unit: 20,
        src: "./images/product.svg",
        freshness: true,
        discount: true,
        measurement: "g"
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack2",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: true,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack3",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: false,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack4",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: true,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack5",
        newPrice: 30,
        oldPrice: 47,
        unit: 20,
        src: "./images/product.svg",
        freshness: false,
        discount: true,
        measurement: "g"
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack6",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: false,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack7",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: false,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack8",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: false,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack9",
        newPrice: 30,
        oldPrice: 47,
        unit: 20,
        src: "./images/product.svg",
        freshness: true,
        discount: true,
        measurement: "g"
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack10",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: true,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack11",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: false,
        discount: false,
        measurement: "g",
    },
    {
        specie: "Juice",
        title: "Mixed Almond nuts juice Pack12",
        price: 20,
        unit: 20,
        src: "./images/product.svg",
        freshness: true,
        discount: false,
        measurement: "g",
    },
]