export { HomePage } from "./home"
export { ContactUsPage } from "./contact-us"
export { AboutUsPage } from "./about-us"
export { CartPage } from "./cart"
export { CategoryPage } from "./category"
export { FaqPage } from "./faq"
export { RegisterPage } from "./register"
export { LogInPage } from "./log-in"